;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagRedirects=(OldTagName="Damadgable",NewTagName="Interaction")
GameplayTagRedirects=(OldTagName="Interaction.Iteam",NewTagName="Interaction.Item")
GameplayTagList=(Tag="Interaction",DevComment="")
GameplayTagList=(Tag="Interaction.Damageable",DevComment="")
GameplayTagList=(Tag="Interaction.Item",DevComment="")
GameplayTagList=(Tag="Interaction.Iteractable",DevComment="")

